/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.app.poo.vista.libro;

import ec.edu.ups.app.poo.controlador.LibroControlador;
import ec.edu.ups.app.poo.modelo.Libro;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author dell
 */
public class VentanaEditarLibro extends javax.swing.JInternalFrame {
     private LibroControlador libroControlador;
    /**
     * Creates new form VentanaEditarLibro
     */
    public VentanaEditarLibro(LibroControlador libroControlador) {
        initComponents();
        this.libroControlador = libroControlador;
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTituloLibro = new javax.swing.JLabel();
        lbAutorLibro = new javax.swing.JLabel();
        lbAñoLibro = new javax.swing.JLabel();
        lbGenero = new javax.swing.JLabel();
        txtTituloEditar = new javax.swing.JTextField();
        txtAutorEditar = new javax.swing.JTextField();
        txtAñoEditar = new javax.swing.JTextField();
        txtEditarLibro = new javax.swing.JButton();
        lbDisponibleLibro1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jComboBoxGenero = new javax.swing.JComboBox<>();
        disponibleBOX = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Editar Libro");

        jPanel2.setBackground(new java.awt.Color(195, 172, 133));
        jPanel2.setToolTipText("");

        lbTituloLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTituloLibro.setText("Titulo");

        lbAutorLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAutorLibro.setText("Autor");

        lbAñoLibro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbAñoLibro.setText("Año");

        lbGenero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbGenero.setText("Género");

        txtTituloEditar.setBackground(new java.awt.Color(143, 119, 65));
        txtTituloEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloEditarActionPerformed(evt);
            }
        });

        txtAutorEditar.setEditable(false);
        txtAutorEditar.setBackground(new java.awt.Color(143, 119, 65));

        txtAñoEditar.setEditable(false);
        txtAñoEditar.setBackground(new java.awt.Color(143, 119, 65));

        txtEditarLibro.setText("Editar");
        txtEditarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditarLibroActionPerformed(evt);
            }
        });

        lbDisponibleLibro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbDisponibleLibro1.setText("Disponible");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jComboBoxGenero.setBackground(new java.awt.Color(143, 119, 65));
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comedia", "Romance", "Ficción", "Misterio", "Terror" }));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });

        disponibleBOX.setBackground(new java.awt.Color(143, 119, 65));
        disponibleBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SI", "NO" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTituloLibro)
                    .addComponent(lbAutorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAñoLibro)
                    .addComponent(lbGenero)
                    .addComponent(lbDisponibleLibro1))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTituloEditar)
                    .addComponent(txtAutorEditar)
                    .addComponent(txtAñoEditar)
                    .addComponent(jComboBoxGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(disponibleBOX, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnBuscar)
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEditarLibro)
                .addGap(94, 94, 94)
                .addComponent(jbLimpiar)
                .addGap(180, 180, 180))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTituloLibro)
                    .addComponent(txtTituloEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAutorLibro)
                    .addComponent(txtAutorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAñoLibro)
                    .addComponent(txtAñoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGenero)
                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDisponibleLibro1)
                    .addComponent(disponibleBOX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiar)
                    .addComponent(txtEditarLibro))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTituloEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloEditarActionPerformed

    private void txtEditarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditarLibroActionPerformed
        // TODO add your handling code here:
        String titulo = txtTituloEditar.getText();
        String autor = txtAutorEditar.getText();
        int año = Integer.parseInt(txtAñoEditar.getText());
        String genero = (String)jComboBoxGenero.getSelectedItem();
        String disponible = (String)disponibleBOX.getSelectedItem();
        libroControlador.update(titulo, autor, año, genero, disponible);
        JOptionPane.showMessageDialog(this, "Se actualizo correctamente!");
        limpiarDatos();
       
    }//GEN-LAST:event_txtEditarLibroActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String titulo = txtTituloEditar.getText();
        Libro libro = libroControlador.read(titulo);
        if(libro!= null){
            txtAutorEditar.setText(libro.getAutor());
            txtAñoEditar.setText(String.valueOf(libro.getAño()));
            disponibleBOX.setSelectedItem(String.valueOf(libro.getDisponible()));
            jComboBoxGenero.setSelectedItem(libro.getGenero());
            txtAutorEditar.setEditable(true);
            txtAñoEditar.setEditable(true);
            disponibleBOX.setEditable(true);
            jComboBoxGenero.setEditable(true);
            txtTituloEditar.setEditable(false);
            
        }else{
            JOptionPane.showMessageDialog(this, "El libro a editar no existe!");
        }
     
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarDatos();
    }
    private void limpiarDatos(){
        txtAutorEditar.setEditable(false);
        txtAñoEditar.setEditable(false);
        disponibleBOX.setEditable(false);
        jComboBoxGenero.setEditable(false);
        txtTituloEditar.setEditable(true);
        txtAutorEditar.setText("");
        txtAñoEditar.setText("");
        txtTituloEditar.setText("");
        
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    public void cambiarIdioma(Locale locale) {
        ResourceBundle mensajes = ResourceBundle.getBundle("mensajes.mensajes", locale);
        ResourceBundle titulos = ResourceBundle.getBundle("titulos.titulos", locale); 
            this.setTitle(titulos.getString("EditarL"));
        lbTituloLibro.setText(mensajes.getString("tituloLibro"));
        lbAutorLibro.setText(mensajes.getString("autorLibro"));
        lbAñoLibro.setText(mensajes.getString("anoLibro"));
        lbGenero.setText(mensajes.getString("Genero"));
        lbDisponibleLibro1.setText(mensajes.getString("disponibleLibro"));
        btnBuscar.setText(mensajes.getString("botonBuscar"));
        txtEditarLibro.setText(mensajes.getString("botonEditar"));
        jbLimpiar.setText(mensajes.getString("botonLimpiar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> disponibleBOX;
    private javax.swing.JComboBox<String> jComboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JLabel lbAutorLibro;
    private javax.swing.JLabel lbAñoLibro;
    private javax.swing.JLabel lbDisponibleLibro1;
    private javax.swing.JLabel lbGenero;
    private javax.swing.JLabel lbTituloLibro;
    private javax.swing.JTextField txtAutorEditar;
    private javax.swing.JTextField txtAñoEditar;
    private javax.swing.JButton txtEditarLibro;
    private javax.swing.JTextField txtTituloEditar;
    // End of variables declaration//GEN-END:variables
}
